### ISSUE TITLE
Trying get 'hello world' example working

### ISSUE THREAD

**Issue by darkofabijan** [mobomo/rack-stream#1]
Hi,

Please check my example at https://github.com/darkofabijan/rack-stream-example.

Note: I had to add `run app`. Rack was complaining about missing `run`.

When I run `curl -i -N http://localhost:3000/` I get exception below:

```
bundle exec thin start -R config.ru -p 3000                             
>> Thin web server (v1.3.1 codename Triple Espresso)
>> Maximum connections set to 1024
>> Listening on 0.0.0.0:3000, CTRL+C to stop
/home/developer/semaphore-stream/.bundle/ruby/1.9.1/gems/rack-stream-0.0.3/lib/rack/stream/app.rb:90:in `block in open!': undefined method `call' for App:Class (NoMethodError)
    from /home/developer/semaphore-stream/.bundle/ruby/1.9.1/gems/rack-stream-0.0.3/lib/rack/stream/app.rb:135:in `block in run_callbacks'
    from /home/developer/semaphore-stream/.bundle/ruby/1.9.1/gems/em-synchrony-1.0.1/lib/em-synchrony.rb:26:in `call'
    from /home/developer/semaphore-stream/.bundle/ruby/1.9.1/gems/em-synchrony-1.0.1/lib/em-synchrony.rb:26:in `block (2 levels) in synchrony'
```

Any ideas?

Thanks,
Darko

**Comment by jch** [comment]
Oops, I had the DSL working with Grape, but I didn't actually test it with a bare rack app. I know where the fix should go, and I'll let you know when I have it pushed.

**Comment by darkofabijan** [comment]
Awesome! Thanks.

**Comment by jch** [comment]
@darkofabijan I forked and made the [fixes for your sample app](https://github.com/darkofabijan/rack-stream-example/pull/1). The docs have also been updated, and you can see the new changes in action. Let me know if you have any more trouble

**Comment by darkofabijan** [comment]
Thanks. It's working. :)
