### ISSUE TITLE
First examples gives error

### ISSUE THREAD

**Issue by phillipp** [mobomo/rack-stream#2]
Hi!

Your first example from the README gives me a 

```
Rack::Lint::LintError at /
Status must be >=100 seen as integer
Ruby    /home/adminz/.rvm/gems/ruby-1.9.3-head/gems/rack-1.4.1/lib/rack/lint.rb: in assert, line 19
Web     GET 192.168.2.148/
```

If I try a small example app like the following, I get the same result

``` ruby
require "rack/stream"
use Rack::Stream

class FooApplication
  class ErbPage
    def each
      (1..1000).each do |i|
        yield i.to_s + "\r\n"
      end
    end
  end

  def call(env)
    [200, {"content-type" => "text/plain"}, ErbPage.new]
  end
end

run FooApplication.new
```

**Comment by jch** [comment]
How are you running the server? Are you using thin? Is this app embedded in another Rack application that does use Rack::Lint?

**Comment by phillipp** [comment]
I use `rackup -s thin`, everything else is posted in the `config.ru` above

**Comment by jch** [comment]
`rackup` implicitly adds `Rack::Lint` to the middleware stack. Async thin uses -1 as a status code to signal that it's an async response. The fix here is to invoke thin directly:

``` sh
thin start -R config.ru
```

When I ran your example, it did expose a bug in how rack-stream handles custom response bodies. I've made the fix and pushed version 0.0.5. Do a gem update and let me know if your examples works after that.

**Comment by phillipp** [comment]
Thanks, that worked.

I was wondering: why does Rack::Stream use a new DSL and thus makes it incompatible with a "normal" rack app? I have a rack server where only one request requires chunked streaming of the response, and Rack::Stream would require a whole rewrite making it practically impossible to impelement that on budget. 

Are there an alternative way that could make this easier?

**Comment by phillipp** [comment]
Oh, I'm sorry, that bug you found made me think it was incompativle. Never mind ;-)

After I got this up & running the only thing left to say is: GREAT WORK!

**Comment by jch** [comment]
@phillipp thanks!

If you don't want to use the DSL. The `Rack::Stream::App` instance is available for direct use via `env['rack.stream']`:

``` ruby
class App
  def call(env)
    env['rack.stream'].chunk("foo")
    [200, {}, ['Hello']]
  end
end

run App.new
```

Best of luck with the experiments. There'll some big upcoming changes that'll allow for ajax long-polling so that this will work with older browsers and non-websocket environments.
